<?php
/**
 * Header
 *
 * Displays all information in head, starts the body tag, contains theme header
 * and nav and starts the main content wrapper
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>
<!DOCTYPE html>
<!--[if IE 8 ]>
	<html class="no-js ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 9 ]>
	<html class="no-js ie9" <?php language_attributes(); ?>>
<![endif]-->
<!--[if gt IE 9]><!-->
<html <?php language_attributes(); ?>><!--<![endif]-->
	<head>
		<?php responsive_mobile_head_top(); ?>
		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" /> 

		<link rel="profile" href="http://gmpg.org/xfn/11">
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
		<?php responsive_mobile_head_bottom(); ?>

		<?php wp_head(); ?>
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin-ext" rel="stylesheet">

		<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/dropdown.js"></script>
	
	
	</head>

<body <?php body_class(); ?> itemscope="itemscope" itemtype="http://schema.org/WebPage">

	<header id="header" class="container-full-width site-header" role="banner" itemscope="itemscope" itemtype="http://schema.org/WPHeader">
	
	<?php responsive_mobile_body_top(); ?>
	<div id="main-menu-container" class="container-full-width">
		<div id="main-menu" class="container">
			<nav id="main-navigation" class="site-navigation" role="navigation" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
				<div id="mobile-current-item"><?php responsive_mobile_menu_title(); ?></div>
				<button id="mobile-nav-button"><span class="accessibile-label"><?php _e( 'Mobile menu toggle', 'responsive-mobile' ); ?></span></button>
				<?php wp_nav_menu(
					array(
						'container'       => 'div',
						'container_class' => 'main-nav',
						'theme_location'  => 'header-menu'
					)
				); ?>
			</nav><!-- #site-navigation -->
		</div><!-- #main-menu -->
	</div><!-- #main-menu-container -->
	
	
<div id="pasek-bottom" class="pasek-dol"></div>
<?php responsive_mobile_header_before(); ?>

		<?php responsive_mobile_header_top(); ?>
		<div class="container">
			<div class="header-row">
				<div id="site-branding">
				<!-- <a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home" itemprop="url"> -->
				
				<picture>
    <source srcset="<?php echo get_stylesheet_directory_uri(); ?>/images/logo-piasmal-small_03.jpg" media="(max-width: 768px)">
    <source srcset="<?php echo get_stylesheet_directory_uri(); ?>/images/logo.jpg">
    <img srcset="<?php echo get_stylesheet_directory_uri(); ?>/images/logo.jpg" alt="Pias-Mal">
</picture>
<!-- </a> -->
				</div>
				
			</div>
		</div>

		<?php responsive_mobile_header_bottom(); ?>
	</header><!-- #header -->
<?php responsive_mobile_header_end(); ?>


<?php responsive_mobile_wrapper(); // before wrapper container hook ?>

<?php
		/**$pagename = get_query_var('pagename');**/
		/**if( ( is_front_page()) ) **/
$pagename = get_query_var('pagename');
if( ( is_front_page()) )  {?>

<?php wp_reset_query(); ?>
<div class="blok-slider container-full-width">

	
<?php 
    echo do_shortcode("[metaslider id=29]"); 
?>


	</div>
			
			
			<?php } else { ?>
			
			<?php } ?>	
	<div id="wrapper" class="site-content container-full-width">
<?php responsive_mobile_wrapper_top(); // before wrapper content hook ?>
<?php responsive_mobile_in_wrapper(); // wrapper hook ?>
